### ISSUE TITLE
Stopped working on recent firefox versions

### ISSUE THREAD

**Issue by iku000888** [thorikawa/FireMobileSimulator#4]
Thanks for this plugin, it has been extremely helpful!

I noticed that after updating my firefox recently,
this plug in stopped working and wanted to share the information.

The chrome version still works, so that is how I am working around the breakage for now.

Thanks!

**Comment by thorikawa** [comment]
This issue is caused by the issue #3 and was already fixed. The updated version 1.2.5 is just released, so please update it.
Thanks!

**Comment by iku000888** [comment]
Thanks! :beer: 
It is great to know that the project is still alive!
